#!/bin/bash

# Chenaniah.org Manual Deployment Script
# Run this script to deploy the application to your server

echo "🚀 Chenaniah.org Deployment Script"
echo "=================================="

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

echo "📦 Step 1: Uploading application to server..."
echo "Please run this command in another terminal:"
echo "scp chenaniah-web.tar.gz barch@15.204.227.47:/home/barch/"
echo ""
echo "Press Enter when upload is complete..."
read

echo "🔧 Step 2: Deploying on server..."
echo "Please SSH into your server and run these commands:"
echo ""
echo "ssh barch@15.204.227.47"
echo "Password: 12345678"
echo ""
echo "Then run these commands on the server:"
echo ""
echo "# Create application directory"
echo "mkdir -p /home/barch/chenaniah-web"
echo "cd /home/barch"
echo ""
echo "# Extract the application"
echo "tar -xzf chenaniah-web.tar.gz -C chenaniah-web/"
echo "cd chenaniah-web"
echo ""
echo "# Install dependencies"
echo "npm install --legacy-peer-deps"
echo ""
echo "# Build the application"
echo "npm run build"
echo ""
echo "# Install PM2 globally"
echo "npm install -g pm2"
echo ""
echo "# Create PM2 configuration"
echo "cat > ecosystem.config.js << 'EOF'"
echo "module.exports = {"
echo "  apps: [{"
echo "    name: 'chenaniah-web',"
echo "    script: 'npm',"
echo "    args: 'start',"
echo "    cwd: '/home/barch/chenaniah-web',"
echo "    instances: 1,"
echo "    autorestart: true,"
echo "    watch: false,"
echo "    max_memory_restart: '1G',"
echo "    env: {"
echo "      NODE_ENV: 'production',"
echo "      PORT: 3000"
echo "    }"
echo "  }]"
echo "}"
echo "EOF"
echo ""
echo "# Start with PM2"
echo "pm2 start ecosystem.config.js"
echo "pm2 save"
echo "pm2 startup"
echo ""
echo "# Check status"
echo "pm2 status"
echo "pm2 logs chenaniah-web"
echo ""
echo "🎉 Deployment complete!"
echo "Your application should be running at: http://15.204.227.47:3000"
