#!/bin/bash

# Chenaniah.org Complete Deployment Script
# This script deploys the Next.js application with domain configuration

echo "🚀 Starting Chenaniah.org deployment with domain configuration..."

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: Please run this script from the project root directory"
    exit 1
fi

# Create deployment package
echo "📦 Creating deployment package..."
tar -czf chenaniah-web.tar.gz \
    --exclude=node_modules \
    --exclude=.next \
    --exclude=.git \
    --exclude=*.log \
    --exclude=.env.local \
    --exclude=.env \
    .

echo "✅ Deployment package created: chenaniah-web.tar.gz"

echo ""
echo "📋 Complete Deployment Instructions for chenaniah.org:"
echo "=================================================="
echo ""
echo "1. Upload the deployment package to your server:"
echo "   scp chenaniah-web.tar.gz barch@15.204.227.47:/home/barch/"
echo ""
echo "2. SSH into your server:"
echo "   ssh barch@15.204.227.47"
echo "   Password: 12345678"
echo ""
echo "3. On the server, run these commands:"
echo ""
echo "   # Create application directory"
echo "   mkdir -p /home/barch/chenaniah-web"
echo "   cd /home/barch"
echo ""
echo "   # Extract the application"
echo "   tar -xzf chenaniah-web.tar.gz -C chenaniah-web/"
echo "   cd chenaniah-web"
echo ""
echo "   # Install dependencies"
echo "   npm install --legacy-peer-deps"
echo ""
echo "   # Build the application"
echo "   npm run build"
echo ""
echo "   # Install PM2 globally"
echo "   npm install -g pm2"
echo ""
echo "   # Create PM2 configuration"
echo "   cat > ecosystem.config.js << 'EOF'"
echo "   module.exports = {"
echo "     apps: [{"
echo "       name: 'chenaniah-web',"
echo "       script: 'npm',"
echo "       args: 'start',"
echo "       cwd: '/home/barch/chenaniah-web',"
echo "       instances: 1,"
echo "       autorestart: true,"
echo "       watch: false,"
echo "       max_memory_restart: '1G',"
echo "       env: {"
echo "         NODE_ENV: 'production',"
echo "         PORT: 3000"
echo "       }"
echo "     }]"
echo "   }"
echo "   EOF"
echo ""
echo "   # Start with PM2"
echo "   pm2 start ecosystem.config.js"
echo "   pm2 save"
echo "   pm2 startup"
echo ""
echo "4. Configure nginx for chenaniah.org domain:"
echo ""
echo "   # Copy nginx configuration"
echo "   sudo cp nginx-chenaniah.conf /etc/nginx/sites-available/chenaniah.org"
echo ""
echo "   # Enable the site"
echo "   sudo ln -s /etc/nginx/sites-available/chenaniah.org /etc/nginx/sites-enabled/"
echo ""
echo "   # Remove default nginx site (if exists)"
echo "   sudo rm -f /etc/nginx/sites-enabled/default"
echo ""
echo "   # Test nginx configuration"
echo "   sudo nginx -t"
echo ""
echo "   # Start nginx"
echo "   sudo systemctl start nginx"
echo "   sudo systemctl enable nginx"
echo ""
echo "5. Set up SSL certificate (run as root):"
echo ""
echo "   # Make SSL setup script executable"
echo "   chmod +x setup-ssl.sh"
echo ""
echo "   # Run SSL setup (this will obtain Let's Encrypt certificate)"
echo "   sudo ./setup-ssl.sh"
echo ""
echo "6. Verify deployment:"
echo ""
echo "   # Check PM2 status"
echo "   pm2 status"
echo ""
echo "   # Check nginx status"
echo "   sudo systemctl status nginx"
echo ""
echo "   # Check if site is accessible"
echo "   curl -I https://chenaniah.org"
echo ""
echo "🎉 Deployment complete!"
echo "Your site should be accessible at: https://chenaniah.org"
echo ""
echo "📋 Important Notes:"
echo "- Make sure your domain DNS is pointing to your server IP (15.204.227.47)"
echo "- The SSL certificate will be automatically renewed"
echo "- Monitor logs with: pm2 logs chenaniah-web"
echo "- Restart nginx after any configuration changes: sudo systemctl restart nginx"
